"""SQLAlchemy 2.x mirror of the §3 DDL.

The ORM is a convenience layer only: `alembic/versions/0001_baseline.py` owns
the schema (triggers, RLS policies, grants and COMMENTs have no ORM
equivalent), and `metadata.create_all` is never called. Constraints and indexes
are declared here with their DDL names so a model diff stays readable, not so
they can be created from Python.

Two rules from §3 are visible in the mappings and matter more than the rest:
  * No CHECK constraint is ever placed on a value Bitrix24 controls — one novel
    CALL_TYPE or failure code must not be able to stall the sync cursor — so the
    Bitrix-supplied columns here are wide and unconstrained on purpose.
  * `calls.has_record` and `calls.result_group` are generated by the database so
    that "has a recording" and the result grouping have exactly one definition,
    shared by filters, summaries and jobs.
"""

from __future__ import annotations

import datetime as dt
import uuid
from decimal import Decimal
from typing import Any

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    DateTime,
    FetchedValue,
    ForeignKey,
    Identity,
    Index,
    Integer,
    LargeBinary,
    Numeric,
    SmallInteger,
    String,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

_TS = DateTime(timezone=True)


class Base(DeclarativeBase):
    """Declarative root.

    Plain (non-dataclass) mapping: every column is optional at construction
    time, so the read-only generated columns of `calls` are simply never
    assigned rather than needing an `init=False` opt-out.
    """


class Portal(Base):
    """Tenant registry plus the single portal (installer) credential.

    §1 decision 16: the credential lives in one row precisely so the
    `token_version` + `SELECT ... FOR UPDATE` single-flight refresh has exactly
    one thing to lock.
    """

    __tablename__ = "portals"
    __table_args__ = (
        UniqueConstraint("member_id", name="portals_member_id_key"),
        CheckConstraint(r"member_id ~ '^[0-9a-f]{32}$'", name="portals_member_id_fmt"),
        CheckConstraint("status IN ('active','uninstalled')", name="portals_status_chk"),
        CheckConstraint(
            "token_status IN ('ok','reauth_required','no_stats_permission',"
            "'method_missing','filter_unsupported')",
            name="portals_token_status_chk",
        ),
        CheckConstraint(
            "crm_mode IN ('off','sync','shadow','mirror')", name="portals_crm_mode_chk"
        ),
        CheckConstraint(
            "crm_opt_out_at IS NULL OR crm_mode = 'off'", name="portals_crm_opt_out_chk"
        ),
        Index("portals_status_idx", "status", postgresql_where=text("status = 'active'")),
        Index("portals_purge_idx", "id", postgresql_where=text("purge_pending")),
        Index("portals_crm_purge_idx", "id", postgresql_where=text("crm_purge_pending")),
    )

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=True), primary_key=True)
    member_id: Mapped[str] = mapped_column(String(32), nullable=False)
    domain: Mapped[str] = mapped_column(String(255), nullable=False)
    protocol_https: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("true")
    )
    client_endpoint: Mapped[str] = mapped_column(String(512), nullable=False)
    server_endpoint: Mapped[str] = mapped_column(
        String(512), nullable=False, server_default=text("'https://oauth.bitrix.info/rest/'")
    )
    status: Mapped[str] = mapped_column(String(16), nullable=False, server_default=text("'active'"))
    app_status: Mapped[str | None] = mapped_column(String(4))
    app_version: Mapped[int | None] = mapped_column(Integer)
    installed_flag: Mapped[bool | None] = mapped_column(Boolean)
    scope: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("''"))
    lang: Mapped[str | None] = mapped_column(String(8))
    timezone: Mapped[str] = mapped_column(String(64), nullable=False, server_default=text("'UTC'"))
    capabilities: Mapped[dict[str, Any]] = mapped_column(
        postgresql.JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    token_user_id: Mapped[int | None] = mapped_column(Integer)
    access_token_enc: Mapped[bytes | None] = mapped_column(LargeBinary)
    refresh_token_enc: Mapped[bytes | None] = mapped_column(LargeBinary)
    token_expires_at: Mapped[dt.datetime | None] = mapped_column(_TS)
    token_refreshed_at: Mapped[dt.datetime | None] = mapped_column(_TS)
    token_admin_verified_at: Mapped[dt.datetime | None] = mapped_column(_TS)
    token_version: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    token_status: Mapped[str] = mapped_column(
        String(24), nullable=False, server_default=text("'ok'")
    )
    application_token_enc: Mapped[bytes | None] = mapped_column(LargeBinary)
    placements: Mapped[dict[str, Any]] = mapped_column(
        postgresql.JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    purge_pending: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false")
    )
    purge_bodies: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false")
    )
    last_event_ts: Mapped[dt.datetime | None] = mapped_column(_TS)
    installed_at: Mapped[dt.datetime] = mapped_column(
        _TS, nullable=False, server_default=func.now()
    )
    install_completed_at: Mapped[dt.datetime | None] = mapped_column(_TS)
    uninstalled_at: Mapped[dt.datetime | None] = mapped_column(_TS)
    last_opened_at: Mapped[dt.datetime | None] = mapped_column(_TS)
    last_admin_opened_at: Mapped[dt.datetime | None] = mapped_column(_TS)
    # CRM mirror (0004, §4.14). `crm_mode` gates the worker's CRM lanes; an administrator's
    # opt-out pins it to `off` (portals_crm_opt_out_chk) and queues the CRM-only purge.
    crm_mode: Mapped[str] = mapped_column(String(8), nullable=False, server_default=text("'sync'"))
    crm_opt_out_at: Mapped[dt.datetime | None] = mapped_column(_TS)
    crm_opt_out_by: Mapped[int | None] = mapped_column(Integer)
    crm_notice_dismissed_by: Mapped[list[int]] = mapped_column(
        postgresql.ARRAY(Integer), nullable=False, server_default=text("'{}'")
    )
    crm_purge_pending: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false")
    )
    created_at: Mapped[dt.datetime] = mapped_column(_TS, nullable=False, server_default=func.now())
    # Maintained by the portals_updated_at trigger, not by the ORM.
    updated_at: Mapped[dt.datetime] = mapped_column(_TS, nullable=False, server_default=func.now())

    # lazy="raise": a 1:1 that was not eagerly loaded must fail loudly at the
    # access site instead of emitting IO from an async attribute read, which
    # would surface as MissingGreenlet at an arbitrary point in a request.
    sync: Mapped[PortalSync | None] = relationship(
        back_populates="portal", uselist=False, lazy="raise", cascade="all, delete-orphan"
    )


class PortalSync(Base):
    """Cursors, throttle state and lease, 1:1 with `portals`.

    Split from `portals` because it is rewritten after every batch and must
    never contend with the credential row's `FOR UPDATE` lock (§3 rationale).
    """

    __tablename__ = "portal_sync"
    __table_args__ = (
        CheckConstraint(
            "backfill_status IN ('pending','head','running','done','failed')",
            name="portal_sync_backfill_chk",
        ),
        CheckConstraint("batch_pages BETWEEN 1 AND 50", name="portal_sync_batch_pages_chk"),
        Index("portal_sync_due_idx", "next_run_at"),
    )

    portal_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("portals.id", ondelete="CASCADE"), primary_key=True
    )
    sync_generation: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    high_id: Mapped[int] = mapped_column(BigInteger, nullable=False, server_default=text("0"))
    low_id: Mapped[int | None] = mapped_column(BigInteger)
    rescan_from_id: Mapped[int | None] = mapped_column(BigInteger)
    backfill_status: Mapped[str] = mapped_column(
        String(16), nullable=False, server_default=text("'pending'")
    )
    backfill_total: Mapped[int | None] = mapped_column(Integer)
    backfill_done: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    backfill_started_at: Mapped[dt.datetime | None] = mapped_column(_TS)
    backfill_finished_at: Mapped[dt.datetime | None] = mapped_column(_TS)
    batch_pages: Mapped[int] = mapped_column(
        SmallInteger, nullable=False, server_default=text("20")
    )
    clean_visits: Mapped[int] = mapped_column(
        SmallInteger, nullable=False, server_default=text("0")
    )
    last_incremental_at: Mapped[dt.datetime | None] = mapped_column(_TS)
    last_rescan_at: Mapped[dt.datetime | None] = mapped_column(_TS)
    last_recheck_at: Mapped[dt.datetime | None] = mapped_column(_TS)
    last_employees_at: Mapped[dt.datetime | None] = mapped_column(_TS)
    last_appinfo_at: Mapped[dt.datetime | None] = mapped_column(_TS)
    next_run_at: Mapped[dt.datetime] = mapped_column(_TS, nullable=False, server_default=func.now())
    lease_owner: Mapped[str | None] = mapped_column(String(64))
    lease_expires_at: Mapped[dt.datetime | None] = mapped_column(_TS)
    run_started_at: Mapped[dt.datetime | None] = mapped_column(_TS)
    # Decimal, never float: §5.6 compares accumulated operating seconds against
    # a limit, and float drift there would silently mis-throttle a portal.
    operating_seconds: Mapped[Decimal | None] = mapped_column(Numeric(8, 2))
    operating_reset_at: Mapped[dt.datetime | None] = mapped_column(_TS)
    throttle_hits: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    consecutive_failures: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("0")
    )
    rejected_rows: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    last_error_code: Mapped[str | None] = mapped_column(String(64))
    last_error_text: Mapped[str | None] = mapped_column(Text)
    last_error_at: Mapped[dt.datetime | None] = mapped_column(_TS)
    # Maintained by the portal_sync_updated_at trigger, not by the ORM.
    updated_at: Mapped[dt.datetime] = mapped_column(_TS, nullable=False, server_default=func.now())

    portal: Mapped[Portal] = relationship(back_populates="sync", lazy="raise")


class SyncMethodBudget(Base):
    """Operating-time state per (portal, Bitrix24 method), statistics excepted (§5.6).

    `portal_sync.operating_*` stays the statistics method's; every other method the worker
    calls is accounted here, because Bitrix24 accounts operating time per method.
    """

    __tablename__ = "sync_method_budgets"

    portal_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("portals.id", ondelete="CASCADE"), primary_key=True
    )
    method: Mapped[str] = mapped_column(String(64), primary_key=True)
    operating_seconds: Mapped[Decimal | None] = mapped_column(Numeric(8, 2))
    operating_reset_at: Mapped[dt.datetime | None] = mapped_column(_TS)
    blocked_until: Mapped[dt.datetime | None] = mapped_column(_TS)
    limit_s: Mapped[Decimal | None] = mapped_column(Numeric(8, 2))
    throttle_hits: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    clean_visits: Mapped[int] = mapped_column(
        SmallInteger, nullable=False, server_default=text("0")
    )
    # Maintained by the sync_method_budgets_updated_at trigger, not by the ORM.
    updated_at: Mapped[dt.datetime] = mapped_column(_TS, nullable=False, server_default=func.now())


class CrmLane(Base):
    """One CRM mirror lane of one portal: its schedule, cursor and failures (§5.10).

    Control plane: id bounds, server timestamps and counters, never a record's values.
    """

    __tablename__ = "crm_lanes"
    __table_args__ = (
        CheckConstraint(
            "status IN ('pending','active','done','parked')", name="crm_lanes_status_chk"
        ),
    )

    portal_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("portals.id", ondelete="CASCADE"), primary_key=True
    )
    lane: Mapped[str] = mapped_column(String(32), primary_key=True)
    status: Mapped[str] = mapped_column(String(16), nullable=False, server_default=text("'pending'"))
    due_at: Mapped[dt.datetime] = mapped_column(_TS, nullable=False, server_default=func.now())
    cursor: Mapped[dict[str, Any]] = mapped_column(
        postgresql.JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    progress_done: Mapped[int] = mapped_column(BigInteger, nullable=False, server_default=text("0"))
    progress_total: Mapped[int | None] = mapped_column(BigInteger)
    last_clean_at: Mapped[dt.datetime | None] = mapped_column(_TS)
    failures: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    paused_until: Mapped[dt.datetime | None] = mapped_column(_TS)
    block_reason: Mapped[str | None] = mapped_column(String(64))
    last_error_code: Mapped[str | None] = mapped_column(String(64))
    last_error_at: Mapped[dt.datetime | None] = mapped_column(_TS)
    # Maintained by the crm_lanes_updated_at trigger, not by the ORM.
    updated_at: Mapped[dt.datetime] = mapped_column(_TS, nullable=False, server_default=func.now())


class AppFlag(Base):
    """A fleet-wide switch an operator flips without a deploy (`crm_mirror` is the first)."""

    __tablename__ = "app_flags"

    name: Mapped[str] = mapped_column(String(64), primary_key=True)
    enabled: Mapped[bool] = mapped_column(Boolean, nullable=False)
    note: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("''"))
    updated_at: Mapped[dt.datetime] = mapped_column(_TS, nullable=False, server_default=func.now())


class Call(Base):
    """Metadata cache of `voximplant.statistic.get`. Never stores audio.

    RLS-protected: reachable only inside `tenant_txn(portal_id)` (§1 decision 8).
    """

    __tablename__ = "calls"
    __table_args__ = (
        UniqueConstraint("portal_id", "bx_id", name="calls_portal_bx_id_key"),
        Index(
            "calls_portal_start_idx",
            "portal_id",
            text("call_start_date DESC"),
            postgresql_include=[
                "portal_user_id",
                "call_type",
                "result_group",
                "call_duration",
                "rest_app_id",
                "has_record",
            ],
        ),
        Index(
            "calls_portal_user_start_idx",
            "portal_id",
            "portal_user_id",
            text("call_start_date DESC"),
        ),
        Index(
            "calls_portal_crm_entity_idx",
            "portal_id",
            "crm_entity_type",
            "crm_entity_id",
            text("call_start_date DESC"),
            postgresql_where=text("crm_entity_id IS NOT NULL"),
        ),
        Index(
            "calls_portal_activity_idx",
            "portal_id",
            "crm_activity_id",
            postgresql_where=text("crm_activity_id IS NOT NULL"),
        ),
        Index("calls_portal_rest_app_idx", "portal_id", "rest_app_id"),
        Index(
            "calls_portal_recheck_idx",
            "portal_id",
            "call_start_date",
            postgresql_where=text(
                "record_file_id IS NULL AND coalesce(call_record_url,'') = '' "
                "AND call_duration > 0 AND record_recheck_count < 2"
            ),
        ),
        Index("calls_portal_refresh_idx", "portal_id", postgresql_where=text("refresh_requested")),
    )

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=True), primary_key=True)
    portal_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("portals.id", ondelete="CASCADE"), nullable=False
    )
    bx_id: Mapped[int] = mapped_column(BigInteger, nullable=False)
    call_id: Mapped[str | None] = mapped_column(String(255))
    external_call_id: Mapped[str | None] = mapped_column(String(255))
    call_category: Mapped[str | None] = mapped_column(String(64))
    call_type: Mapped[int | None] = mapped_column(SmallInteger)
    call_start_date: Mapped[dt.datetime] = mapped_column(_TS, nullable=False)
    call_duration: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    call_failed_code: Mapped[str | None] = mapped_column(String(32))
    call_failed_reason: Mapped[str | None] = mapped_column(Text)
    portal_user_id: Mapped[int | None] = mapped_column(Integer)
    portal_number: Mapped[str | None] = mapped_column(String(128))
    phone_number: Mapped[str | None] = mapped_column(String(128))
    crm_entity_type: Mapped[str | None] = mapped_column(String(32))
    crm_entity_id: Mapped[int | None] = mapped_column(Integer)
    crm_activity_id: Mapped[int | None] = mapped_column(BigInteger)
    # NUMERIC because Bitrix24 serializes costs as "0.0000" strings (§3).
    cost: Mapped[Decimal | None] = mapped_column(Numeric(12, 4))
    cost_currency: Mapped[str | None] = mapped_column(String(8))
    call_vote: Mapped[int | None] = mapped_column(SmallInteger)
    call_record_url: Mapped[str | None] = mapped_column(Text)
    record_file_id: Mapped[int | None] = mapped_column(BigInteger)
    record_duration: Mapped[int | None] = mapped_column(Integer)
    rest_app_id: Mapped[int | None] = mapped_column(Integer)
    rest_app_name: Mapped[str | None] = mapped_column(String(255))
    transcript_id: Mapped[int | None] = mapped_column(BigInteger)
    transcript_pending: Mapped[bool | None] = mapped_column(Boolean)
    session_id: Mapped[int | None] = mapped_column(BigInteger)
    redial_attempt: Mapped[int | None] = mapped_column(SmallInteger)
    comment: Mapped[str | None] = mapped_column(Text)
    call_log: Mapped[str | None] = mapped_column(Text)

    # GENERATED ALWAYS ... STORED in §3. Mapped read-only: Postgres produces the
    # value, the ORM never emits it in an INSERT or UPDATE, and it is read back
    # from the row. Assigning either attribute is a bug.
    has_record: Mapped[bool] = mapped_column(Boolean, server_default=FetchedValue())
    result_group: Mapped[str] = mapped_column(String(16), server_default=FetchedValue())

    record_recheck_count: Mapped[int] = mapped_column(
        SmallInteger, nullable=False, server_default=text("0")
    )
    refresh_requested: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false")
    )
    first_seen_at: Mapped[dt.datetime] = mapped_column(
        _TS, nullable=False, server_default=func.now()
    )
    last_synced_at: Mapped[dt.datetime] = mapped_column(
        _TS, nullable=False, server_default=func.now()
    )
    content_changed_at: Mapped[dt.datetime | None] = mapped_column(_TS)


class Employee(Base):
    """Per-portal `user_brief` cache; RLS-protected like `calls`.

    Dismissed users are kept (`active=false`) because their historical calls
    remain and the UI must still be able to name them (§3).
    """

    __tablename__ = "employees"
    __table_args__ = (Index("employees_stale_idx", "portal_id", text("fetched_at NULLS FIRST")),)

    portal_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("portals.id", ondelete="CASCADE"), primary_key=True
    )
    bx_user_id: Mapped[int] = mapped_column(Integer, primary_key=True)
    name: Mapped[str | None] = mapped_column(String(255))
    last_name: Mapped[str | None] = mapped_column(String(255))
    second_name: Mapped[str | None] = mapped_column(String(255))
    work_position: Mapped[str | None] = mapped_column(String(255))
    photo_url: Mapped[str | None] = mapped_column(Text)
    active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("true"))
    found: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("true"))
    departments: Mapped[list[int]] = mapped_column(
        postgresql.ARRAY(Integer), nullable=False, server_default=text("'{}'")
    )
    # UF_PHONE_INNER: the internal extension, shown beside the name in the employee
    # filter. Free text at Bitrix24, so no CHECK and a width that tolerates a portal
    # storing a whole number in it.
    phone_inner: Mapped[str | None] = mapped_column(String(32))
    # NULL = placeholder inserted by the call upsert for an unseen PORTAL_USER_ID;
    # the refresh job takes NULLs first (§7).
    fetched_at: Mapped[dt.datetime | None] = mapped_column(_TS)


class CrmContext(Base):
    """Resolved CRM entity -> the keys a CRM tab must match; RLS-protected.

    `entity_type` is ours (it comes from the PLACEMENT allowlist, not from a
    Bitrix payload), which is why it is the one enum here that is CHECKed (§3).
    """

    __tablename__ = "crm_contexts"
    __table_args__ = (
        CheckConstraint(
            "entity_type IN ('DEAL','LEAD','CONTACT','COMPANY')", name="crm_contexts_type_chk"
        ),
        Index("crm_contexts_age_idx", "resolved_at"),
    )

    portal_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("portals.id", ondelete="CASCADE"), primary_key=True
    )
    entity_type: Mapped[str] = mapped_column(String(16), primary_key=True)
    entity_id: Mapped[int] = mapped_column(Integer, primary_key=True)
    entity_keys: Mapped[list[Any]] = mapped_column(
        postgresql.JSONB, nullable=False, server_default=text("'[]'::jsonb")
    )
    activity_ids: Mapped[list[int]] = mapped_column(
        postgresql.ARRAY(BigInteger), nullable=False, server_default=text("'{}'")
    )
    resolved_by_user_id: Mapped[int | None] = mapped_column(Integer)
    # §4.8: a read is served only from a row at least as fresh as the JWT, so a
    # privileged user's resolution is never replayed for someone without rights.
    resolved_at: Mapped[dt.datetime] = mapped_column(_TS, nullable=False, server_default=func.now())


#: The columns a tombstone NULLs (crm_items_tombstone_chk); everything D-3 lets us store.
CRM_ITEM_DATA_COLUMNS: tuple[str, ...] = (
    "category_id",
    "stage_id",
    "stage_semantic",
    "assigned_by_id",
    "created_time",
    "updated_time",
    "moved_time",
    "closed",
    "opportunity",
    "currency_id",
    "lead_id",
    "contact_ids",
    "company_id",
    "utm_source",
    "utm_medium",
    "utm_campaign",
    "utm_content",
    "utm_term",
)


class CrmItem(Base):
    """The CRM mirror: one deal (`entity_type_id` 2) or lead (1), D-3 fields only (§4.14).

    RLS-protected like `calls`. No CHECK on a Bitrix-controlled value, for the reason §3 gives
    for `calls`: one odd stage id must never stall a lane.
    """

    __tablename__ = "crm_items"
    __table_args__ = (
        CheckConstraint("entity_type_id IN (1, 2)", name="crm_items_entity_chk"),
        CheckConstraint(
            "delete_reason IN ('not_found','evicted')", name="crm_items_delete_reason_chk"
        ),
        Index(
            "crm_items_deal_created_idx",
            "portal_id",
            "created_time",
            postgresql_include=["category_id", "assigned_by_id", "stage_id", "stage_semantic"],
            postgresql_where=text("entity_type_id = 2 AND deleted_at IS NULL"),
        ),
        Index(
            "crm_items_deal_updated_idx",
            "portal_id",
            "updated_time",
            postgresql_where=text("entity_type_id = 2 AND deleted_at IS NULL"),
        ),
        Index(
            "crm_items_deal_closed_idx",
            "portal_id",
            "moved_time",
            postgresql_where=text("entity_type_id = 2 AND closed AND deleted_at IS NULL"),
        ),
        Index(
            "crm_items_lead_created_idx",
            "portal_id",
            "created_time",
            postgresql_where=text("entity_type_id = 1 AND deleted_at IS NULL"),
        ),
        Index(
            "crm_items_assignee_idx",
            "portal_id",
            "entity_type_id",
            "assigned_by_id",
            "created_time",
            postgresql_where=text("deleted_at IS NULL"),
        ),
        Index(
            "crm_items_company_idx",
            "portal_id",
            "company_id",
            postgresql_where=text("company_id IS NOT NULL AND deleted_at IS NULL"),
        ),
        Index(
            "crm_items_tombstone_idx",
            "portal_id",
            "deleted_at",
            postgresql_where=text("deleted_at IS NOT NULL"),
        ),
        Index(
            "crm_items_unreadable_idx",
            "portal_id",
            "unreadable_since",
            postgresql_where=text("unreadable_since IS NOT NULL"),
        ),
    )

    portal_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("portals.id", ondelete="CASCADE"), primary_key=True
    )
    entity_type_id: Mapped[int] = mapped_column(SmallInteger, primary_key=True)
    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    category_id: Mapped[int | None] = mapped_column(Integer)
    stage_id: Mapped[str | None] = mapped_column(String(128))
    stage_semantic: Mapped[str | None] = mapped_column(String(1))
    assigned_by_id: Mapped[int | None] = mapped_column(Integer)
    created_time: Mapped[dt.datetime | None] = mapped_column(_TS)
    updated_time: Mapped[dt.datetime | None] = mapped_column(_TS)
    moved_time: Mapped[dt.datetime | None] = mapped_column(_TS)
    closed: Mapped[bool | None] = mapped_column(Boolean)
    # Unconstrained NUMERIC: an absurd amount on one portal must not abort a chunk.
    opportunity: Mapped[Decimal | None] = mapped_column(Numeric)
    currency_id: Mapped[str | None] = mapped_column(String(16))
    lead_id: Mapped[int | None] = mapped_column(BigInteger)
    contact_ids: Mapped[list[int] | None] = mapped_column(postgresql.ARRAY(BigInteger))
    company_id: Mapped[int | None] = mapped_column(BigInteger)
    utm_source: Mapped[str | None] = mapped_column(Text)
    utm_medium: Mapped[str | None] = mapped_column(Text)
    utm_campaign: Mapped[str | None] = mapped_column(Text)
    utm_content: Mapped[str | None] = mapped_column(Text)
    utm_term: Mapped[str | None] = mapped_column(Text)
    # The worker's clock before the request that produced this version: an upsert writes only
    # when it is not older, so a slow page never overwrites a newer read.
    read_at: Mapped[dt.datetime] = mapped_column(_TS, nullable=False)
    synced_at: Mapped[dt.datetime] = mapped_column(_TS, nullable=False, server_default=func.now())
    content_changed_at: Mapped[dt.datetime | None] = mapped_column(_TS)
    deleted_at: Mapped[dt.datetime | None] = mapped_column(_TS)
    delete_reason: Mapped[str | None] = mapped_column(String(16))
    unreadable_since: Mapped[dt.datetime | None] = mapped_column(_TS)


class CrmFunnel(Base):
    """A deal funnel, or the lead pipeline as category 0, with its name (G0 Q1)."""

    __tablename__ = "crm_funnels"
    __table_args__ = (CheckConstraint("entity_type_id IN (1, 2)", name="crm_funnels_entity_chk"),)

    portal_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("portals.id", ondelete="CASCADE"), primary_key=True
    )
    entity_type_id: Mapped[int] = mapped_column(SmallInteger, primary_key=True)
    category_id: Mapped[int] = mapped_column(Integer, primary_key=True)
    name: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("''"))
    sort: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    is_default: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("false"))
    seen_at: Mapped[dt.datetime] = mapped_column(_TS, nullable=False, server_default=func.now())
    missing_since: Mapped[dt.datetime | None] = mapped_column(_TS)


class CrmStage(Base):
    """A stage of one funnel, keyed by the (category, status) pair (`deals.py::Stage`)."""

    __tablename__ = "crm_stages"
    __table_args__ = (CheckConstraint("entity_type_id IN (1, 2)", name="crm_stages_entity_chk"),)

    portal_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("portals.id", ondelete="CASCADE"), primary_key=True
    )
    entity_type_id: Mapped[int] = mapped_column(SmallInteger, primary_key=True)
    category_id: Mapped[int] = mapped_column(Integer, primary_key=True)
    status_id: Mapped[str] = mapped_column(String(128), primary_key=True)
    name: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("''"))
    sort: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    semantic: Mapped[str] = mapped_column(String(1), nullable=False, server_default=text("'P'"))
    seen_at: Mapped[dt.datetime] = mapped_column(_TS, nullable=False, server_default=func.now())
    missing_since: Mapped[dt.datetime | None] = mapped_column(_TS)


class CrmDirty(Base):
    """A record id to re-read, and why. Only ids: values always come from a re-read."""

    __tablename__ = "crm_dirty"
    __table_args__ = (
        CheckConstraint("entity_type_id IN (1, 2, 3, 4)", name="crm_dirty_entity_chk"),
        Index("crm_dirty_due_idx", "portal_id", "not_before"),
    )

    portal_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("portals.id", ondelete="CASCADE"), primary_key=True
    )
    entity_type_id: Mapped[int] = mapped_column(SmallInteger, primary_key=True)
    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    reasons: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    # A refresh deletes the row only WHERE seq equals what it read, so a mark that arrives
    # mid-refresh survives for the next pass.
    seq: Mapped[int] = mapped_column(BigInteger, nullable=False, server_default=text("1"))
    first_marked_at: Mapped[dt.datetime] = mapped_column(
        _TS, nullable=False, server_default=func.now()
    )
    not_before: Mapped[dt.datetime] = mapped_column(_TS, nullable=False, server_default=func.now())
    held_until: Mapped[dt.datetime | None] = mapped_column(_TS)
    attempts: Mapped[int] = mapped_column(SmallInteger, nullable=False, server_default=text("0"))


class RestLog(Base):
    """Moderation log of both directions (§6). Control-plane table: no RLS.

    Written in its own short transaction so a failed work transaction still
    leaves the exchange logged; bodies arrive here already redacted by
    `app.security.redact`.
    """

    __tablename__ = "rest_log"
    __table_args__ = (
        CheckConstraint("direction IN ('out','in')", name="rest_log_direction_chk"),
        CheckConstraint(
            "kind IN ('rest','oauth','event','open','install')", name="rest_log_kind_chk"
        ),
        Index("rest_log_ts_idx", "ts"),
        Index("rest_log_portal_ts_idx", "portal_id", text("ts DESC")),
    )

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=True), primary_key=True)
    ts: Mapped[dt.datetime] = mapped_column(_TS, nullable=False, server_default=func.now())
    # Nullable: install-time exchanges happen before the portal row exists and
    # rejected events of unknown portals must still be logged; `member_id`
    # keeps the attribution in both cases.
    portal_id: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("portals.id", ondelete="SET NULL")
    )
    member_id: Mapped[str | None] = mapped_column(String(32))
    correlation_id: Mapped[uuid.UUID | None] = mapped_column(postgresql.UUID(as_uuid=True))
    direction: Mapped[str] = mapped_column(String(3), nullable=False)
    kind: Mapped[str] = mapped_column(String(16), nullable=False)
    method: Mapped[str] = mapped_column(String(128), nullable=False)
    url: Mapped[str] = mapped_column(Text, nullable=False)
    token_user_id: Mapped[int | None] = mapped_column(Integer)
    request: Mapped[dict[str, Any] | None] = mapped_column(postgresql.JSONB)
    http_status: Mapped[int | None] = mapped_column(SmallInteger)
    error_code: Mapped[str | None] = mapped_column(String(64))
    response: Mapped[dict[str, Any] | None] = mapped_column(postgresql.JSONB)
    response_bytes: Mapped[int | None] = mapped_column(Integer)
    truncated: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("false"))
    time_block: Mapped[dict[str, Any] | None] = mapped_column(postgresql.JSONB)
    duration_ms: Mapped[int | None] = mapped_column(Integer)


class PortalEvent(Base):
    """Lifecycle audit that outlives `rest_log` retention. Control-plane: no RLS.

    `details` never contains tokens (§3) — this is the first table support greps
    for a misbehaving portal.
    """

    __tablename__ = "portal_events"
    __table_args__ = (Index("portal_events_portal_idx", "portal_id", text("created_at DESC")),)

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=True), primary_key=True)
    portal_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("portals.id", ondelete="CASCADE"), nullable=False
    )
    kind: Mapped[str] = mapped_column(String(32), nullable=False)
    user_id: Mapped[int | None] = mapped_column(Integer)
    details: Mapped[dict[str, Any]] = mapped_column(
        postgresql.JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    created_at: Mapped[dt.datetime] = mapped_column(_TS, nullable=False, server_default=func.now())
